; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                         = 10200107-x86_64 macOS      
[ DataSettings ]
datatype                    = snDistance                 
MissingBaseSymbol           = ?                          
IdenticalBaseSymbol         = .                          
GapSymbol                   = -                          
Labelled Sites              = All Sites                  
Labels to Include           =                            
[ ProcessTypes ]
ppInfer                     = true                       
ppME                        = true                       
[ AnalysisSettings ]
Analysis                    = Phylogeny Reconstruction   
Scope                       = All Selected Taxa          
Statistical Method          = Minimum Evolution method   
Tree Inference Options      = ====================       
ME Heuristic Method         = Close-Neighbor-Interchange (CNI)
Initial Tree for ME         = Obtain initial tree by Neighbor-Joining
ME Search Level             = 1                          
System Resource Usage       = ====================       
Number of Threads           = 1                          
Has Time Limit              = False                      
Maximum Execution Time      = -1                         
