; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                        = 10191107-x86_64 macOS     
[ DataSettings ]
datatype                   = snDistance                
MissingBaseSymbol          = ?                         
IdenticalBaseSymbol        = .                         
GapSymbol                  = -                         
Labelled Sites             = All Sites                 
Labels to Include          =                           
[ ProcessTypes ]
ppInfer                    = true                      
ppUPGMA                    = true                      
[ AnalysisSettings ]
Analysis                   = Phylogeny Reconstruction  
Scope                      = All Selected Taxa         
Statistical Method         = UPGMA                     
System Resource Usage      = ====================      
Number of Threads          = 1                         
Has Time Limit             = False                     
Maximum Execution Time     = -1                        
